### ISSUE TITLE
exit code: 2

### ISSUE THREAD

**Issue by skyfony** [trumank/patternsleuth#8]
![1](https://github.com/user-attachments/assets/15455c28-0d56-4574-af0b-9bfaa40afb8c)
![2](https://github.com/user-attachments/assets/998d0f2b-2fe4-4160-a4f1-76426a000466)
Hello! 
When I try to use cargo run --release, I get this error (screenshot 1)
When I try to use exe scan, I get this results (screenshot 2)
Help me to fix, please.

**Comment by trumank** [comment]
Exit code 2 is normal if command is invalid or empty. What is UAGame.exe? Other than than the terminal escape characters not properly rendering I don't see anything wrong here.

**Comment by skyfony** [comment]
> Exit code 2 is normal if command is invalid or empty. What is UAGame.exe? Other than than the terminal escape characters not properly rendering I don't see anything wrong here.

Arena Breakout Infinite
